// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestKalkultor
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Test Semua Fungsi Kalkultor
        /// </summary>
        public void TestKalkulator()
        {
            #region Variable Declarations
            WpfTitleBar uIMyCalculatorv1TitleBar = this.UIMyCalculatorv1Window.UIMyCalculatorv1TitleBar;
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            WpfButton uIItem8Button = this.UIMyCalculatorv1Window.UIItem8Button;
            WpfButton uIItem7Button = this.UIMyCalculatorv1Window.UIItem7Button;
            WpfButton uIItem4Button = this.UIMyCalculatorv1Window.UIItem4Button;
            WpfButton uIItem5Button = this.UIMyCalculatorv1Window.UIItem5Button;
            WpfButton uIItem6Button = this.UIMyCalculatorv1Window.UIItem6Button;
            WpfButton uIItem9Button = this.UIMyCalculatorv1Window.UIItem9Button;
            WpfButton uIItem3Button = this.UIMyCalculatorv1Window.UIItem3Button;
            WpfButton uIItem2Button = this.UIMyCalculatorv1Window.UIItem2Button;
            WpfButton uIItem1Button = this.UIMyCalculatorv1Window.UIItem1Button;
            WpfButton uIItem0Button = this.UIMyCalculatorv1Window.UIItem0Button;
            WpfButton uIRButton = this.UIMyCalculatorv1Window.UIRButton;
            WpfButton uIItemButton = this.UIMyCalculatorv1Window.UIItemButton;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            WpfButton uIItemButton2 = this.UIMyCalculatorv1Window.UIItemButton2;
            WpfButton uIItemButton3 = this.UIMyCalculatorv1Window.UIItemButton3;
            WpfButton uIItemButton4 = this.UIMyCalculatorv1Window.UIItemButton4;
            #endregion

            // Click 'MyCalculator v1' title bar
            Mouse.Click(uIMyCalculatorv1TitleBar, new Point(59, 2));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(26, 8));

            // Click '8' button
            Mouse.Click(uIItem8Button, new Point(8, 15));

            // Click '7' button
            Mouse.Click(uIItem7Button, new Point(33, 15));

            // Click '4' button
            Mouse.Click(uIItem4Button, new Point(32, 9));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(7, 10));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(23, 16));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(29, 18));

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(17, 28));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(19, 17));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(28, 17));

            // Double-Click '0' button
            Mouse.DoubleClick(uIItem0Button, new Point(29, 10));

            // Double-Click '0' button
            Mouse.DoubleClick(uIItem0Button, new Point(29, 10));

            // Double-Click '1' button
            Mouse.DoubleClick(uIItem1Button, new Point(27, 23));

            // Click '4' button
            Mouse.Click(uIItem4Button, new Point(32, 8));

            // Click '7' button
            Mouse.Click(uIItem7Button, new Point(22, 6));

            // Click '8' button
            Mouse.Click(uIItem8Button, new Point(22, 12));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(30, 21));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(30, 21));

            // Click 'R' button
            Mouse.Click(uIRButton, new Point(30, 21));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(25, 15));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(25, 15));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(29, 19));

            // Click 'R' button
            Mouse.Click(uIRButton, new Point(22, 14));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(22, 14));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(22, 14));

            // Click 'R' button
            Mouse.Click(uIRButton, new Point(22, 14));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(29, 17));

            // Click '8' button
            Mouse.Click(uIItem8Button, new Point(31, 17));

            // Click '/' button
            Mouse.Click(uIItemButton, new Point(15, 16));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(32, 14));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(46, 24));

            // Click '+' button
            Mouse.Click(uIItemButton2, new Point(27, 17));

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(27, 13));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(45, 15));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(25, 12));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(33, 14));

            // Click '*' button
            Mouse.Click(uIItemButton3, new Point(16, 18));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(56, 15));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(28, 17));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(30, 15));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(29, 18));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(29, 18));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(29, 18));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(22, 16));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(32, 10));

            // Click '/' button
            Mouse.Click(uIItemButton, new Point(20, 21));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(34, 11));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(44, 6));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(32, 9));

            // Click '*' button
            Mouse.Click(uIItemButton3, new Point(18, 20));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(26, 15));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(26, 12));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(67, 22));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(16, 15));

            // Click '*' button
            Mouse.Click(uIItemButton3, new Point(25, 5));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(23, 15));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(49, 12));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(28, 20));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(34, 9));

            // Click '*' button
            Mouse.Click(uIItemButton3, new Point(17, 10));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(25, 15));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(52, 18));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(15, 11));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(15, 11));

            // Click '8' button
            Mouse.Click(uIItem8Button, new Point(24, 17));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(44, 24));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(9, 6));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(10, 6));

            // Click 'R' button
            Mouse.Click(uIRButton, new Point(12, 7));

            // Click '-' button
            Mouse.Click(uIItemButton4, new Point(23, 26));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(23, 20));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(38, 16));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(24, 14));

            // Click 'R' button
            Mouse.Click(uIRButton, new Point(24, 14));

            // Click 'R' button
            Mouse.Click(uIRButton, new Point(20, 13));

            // Click '+' button
            Mouse.Click(uIItemButton2, new Point(21, 12));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(8, 9));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(47, 19));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(12, 11));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(12, 11));

            // Click '-' button
            Mouse.Click(uIItemButton4, new Point(26, 12));

            // Click '8' button
            Mouse.Click(uIItem8Button, new Point(15, 8));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(50, 18));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(18, 17));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(17, 16));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(17, 16));

            // Click 'R' button
            Mouse.Click(uIRButton, new Point(17, 16));

            // Click '-' button
            Mouse.Click(uIItemButton4, new Point(18, 15));

            // Click '8' button
            Mouse.Click(uIItem8Button, new Point(20, 17));

            // Click '+' button
            Mouse.Click(uIItemButton2, new Point(22, 13));

            // Click '-' button
            Mouse.Click(uIItemButton4, new Point(19, 15));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(30, 14));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(53, 13));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(7, 24));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(7, 24));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(7, 24));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(7, 24));

            // Click 'R' button
            Mouse.Click(uIRButton, new Point(7, 24));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(22, 19));

            // Click '-' button
            Mouse.Click(uIItemButton4, new Point(17, 16));

            // Click '8' button
            Mouse.Click(uIItem8Button, new Point(21, 13));

            // Click '-' button
            Mouse.Click(uIItemButton4, new Point(18, 13));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(13, 14));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(53, 13));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(31, 9));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(21, 16));

            // Click '4' button
            Mouse.Click(uIItem4Button, new Point(34, 13));

            // Click '-' button
            Mouse.Click(uIItemButton4, new Point(8, 11));

            // Click '7' button
            Mouse.Click(uIItem7Button, new Point(17, 15));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(67, 19));
        }
        
        /// <summary>
        /// TestResultKalkulator - Use 'TestResultKalkulatorExpectedValues' to pass parameters into this method.
        /// </summary>
        public void TestResultKalkulator()
        {
            #region Variable Declarations
            WpfEdit uITBEdit = this.UIMyCalculatorv1Window.UITBEdit;
            #endregion

            // Verify that the 'Text' property of 'tb' text box equals '4-7=-3'
            Assert.AreEqual(this.TestResultKalkulatorExpectedValues.UITBEditText, uITBEdit.Text, "Hasil Test Tidak Sesuai");
        }
        
        /// <summary>
        /// Testing ke 2
        /// </summary>
        public void TestKalkulator2()
        {
            #region Variable Declarations
            WpfTitleBar uIMyCalculatorv1TitleBar = this.UIMyCalculatorv1Window.UIMyCalculatorv1TitleBar;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            WpfButton uIItem2Button = this.UIMyCalculatorv1Window.UIItem2Button;
            WpfButton uIItem3Button = this.UIMyCalculatorv1Window.UIItem3Button;
            WpfButton uIItem6Button = this.UIMyCalculatorv1Window.UIItem6Button;
            WpfButton uIItem5Button = this.UIMyCalculatorv1Window.UIItem5Button;
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            WpfButton uIItem1Button = this.UIMyCalculatorv1Window.UIItem1Button;
            WpfButton uIItem4Button = this.UIMyCalculatorv1Window.UIItem4Button;
            WpfButton uIRButton = this.UIMyCalculatorv1Window.UIRButton;
            WinWindow uIMyCalculatorv1Window1 = this.UIMyCalculatorv1Window1;
            WpfButton uIItemButton4 = this.UIMyCalculatorv1Window.UIItemButton4;
            WpfButton uIItem0Button = this.UIMyCalculatorv1Window.UIItem0Button;
            WpfButton uIItemButton2 = this.UIMyCalculatorv1Window.UIItemButton2;
            WpfButton uIItem9Button = this.UIMyCalculatorv1Window.UIItem9Button;
            WpfButton uIItemButton = this.UIMyCalculatorv1Window.UIItemButton;
            #endregion

            // Click 'MyCalculator v1' title bar
            Mouse.Click(uIMyCalculatorv1TitleBar, new Point(106, 7));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(59, 17));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(12, 17));

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(11, 11));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(14, 21));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(30, 22));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(27, 17));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(18, 17));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(24, 18));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(11, 11));

            // Click '4' button
            Mouse.Click(uIItem4Button, new Point(24, 25));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(33, 18));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(25, 17));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(52, 6));

            // Click 'R' button
            Mouse.Click(uIRButton, new Point(16, 16));

            // Click 'MyCalculator v1' window
            Mouse.Click(uIMyCalculatorv1Window1, new Point(95, 178));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(33, 12));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(30, 17));

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(19, 8));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(22, 19));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(33, 10));

            // Double-Click 'Del' button
            Mouse.DoubleClick(uIDelButton, new Point(27, 17));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(26, 19));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(27, 13));

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(21, 13));

            // Click '-' button
            Mouse.Click(uIItemButton4, new Point(25, 13));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(24, 14));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(59, 18));

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(22, 8));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(58, 16));

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(15, 8));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(14, 13));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(27, 7));

            // Click 'MyCalculator v1' title bar
            Mouse.Click(uIMyCalculatorv1TitleBar, new Point(95, -1));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(34, 9));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(17, 25));

            // Click '-' button
            Mouse.Click(uIItemButton4, new Point(29, 10));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(34, 19));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(38, 6));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(25, 8));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(33, 17));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(30, 7));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(23, 12));

            // Click '+' button
            Mouse.Click(uIItemButton2, new Point(26, 12));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(21, 13));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(55, 14));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(33, 18));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(18, 10));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(31, 22));

            // Click '/' button
            Mouse.Click(uIItemButton, new Point(23, 15));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(9, 15));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(52, 15));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(22, 16));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(30, 12));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(19, 7));

            // Click '+' button
            Mouse.Click(uIItemButton2, new Point(28, 15));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(26, 9));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(23, 11));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(42, 14));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(33, 6));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(35, 13));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(23, 12));

            // Click '-' button
            Mouse.Click(uIItemButton4, new Point(32, 16));

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(15, 16));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(53, 15));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(19, 8));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(18, 13));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(17, 7));

            // Click '-' button
            Mouse.Click(uIItemButton4, new Point(21, 15));

            // Click '+' button
            Mouse.Click(uIItemButton2, new Point(24, 17));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(25, 10));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(29, 10));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(49, 12));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(23, 15));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(21, 6));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(30, 15));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(27, 15));

            // Click '+' button
            Mouse.Click(uIItemButton2, new Point(21, 16));

            // Click '-' button
            Mouse.Click(uIItemButton4, new Point(29, 17));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(26, 6));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(22, 21));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(38, 10));
        }
        
        /// <summary>
        /// Test Resul2
        /// </summary>
        public void TestResultKalkulator2()
        {
            #region Variable Declarations
            WpfEdit uITBEdit = this.UIMyCalculatorv1Window.UITBEdit;
            #endregion

            // Verify that the 'Text' property of 'tb' text box equals '02+-02=0'
            Assert.AreEqual(this.TestResultKalkulator2ExpectedValues.UITBEditText, uITBEdit.Text, "Test Belum Sesuai");
        }
        
        /// <summary>
        /// Testing ke 3
        /// </summary>
        public void TestKalkulator3()
        {
            #region Variable Declarations
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            WpfButton uIItem8Button = this.UIMyCalculatorv1Window.UIItem8Button;
            WinWindow uIMyCalculatorv1Window1 = this.UIMyCalculatorv1Window1;
            WpfButton uIItem9Button = this.UIMyCalculatorv1Window.UIItem9Button;
            WpfButton uIItemButton = this.UIMyCalculatorv1Window.UIItemButton;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            WpfButton uIItem7Button = this.UIMyCalculatorv1Window.UIItem7Button;
            WpfButton uIItemButton3 = this.UIMyCalculatorv1Window.UIItemButton3;
            WpfButton uIOffButton = this.UIMyCalculatorv1Window.UIOffButton;
            #endregion

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(39, 9));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(18, 14));

            // Click '8' button
            Mouse.Click(uIItem8Button, new Point(26, 21));

            // Click 'MyCalculator v1' window
            Mouse.Click(uIMyCalculatorv1Window1, new Point(170, 163));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(13, 13));

            // Click '/' button
            Mouse.Click(uIItemButton, new Point(27, 16));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(29, 20));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(50, 19));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(26, 18));

            // Click '7' button
            Mouse.Click(uIItem7Button, new Point(28, 23));

            // Click '*' button
            Mouse.Click(uIItemButton3, new Point(19, 18));

            // Click '8' button
            Mouse.Click(uIItem8Button, new Point(19, 13));

            // Click 'Off' button
            Mouse.Click(uIOffButton, new Point(48, 22));
        }
        
        /// <summary>
        /// TestResultKalkulator3 - Use 'TestResultKalkulator3ExpectedValues' to pass parameters into this method.
        /// </summary>
        public void TestResultKalkulator3()
        {
            #region Variable Declarations
            WpfWindow uIMyCalculatorv1Window = this.UIMyCalculatorv1Window;
            #endregion

            // Verify that the 'Enabled' property of 'MyCalculator v1' window equals 'True'
            Assert.AreEqual(this.TestResultKalkulator3ExpectedValues.UIMyCalculatorv1WindowEnabled, uIMyCalculatorv1Window.Enabled);
        }
        
        /// <summary>
        /// Testing ke 4
        /// </summary>
        public void TestKalkulator4()
        {
            #region Variable Declarations
            WpfTitleBar uIMyCalculatorv1TitleBar = this.UIMyCalculatorv1Window.UIMyCalculatorv1TitleBar;
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            WpfButton uIItem5Button = this.UIMyCalculatorv1Window.UIItem5Button;
            WpfButton uIItemButton3 = this.UIMyCalculatorv1Window.UIItemButton3;
            WpfButton uIItem6Button = this.UIMyCalculatorv1Window.UIItem6Button;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            WpfButton uIItem8Button = this.UIMyCalculatorv1Window.UIItem8Button;
            WpfButton uIItem9Button = this.UIMyCalculatorv1Window.UIItem9Button;
            WpfButton uIItemButton = this.UIMyCalculatorv1Window.UIItemButton;
            #endregion

            // Click 'MyCalculator v1' title bar
            Mouse.Click(uIMyCalculatorv1TitleBar, new Point(71, 0));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(17, 16));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(30, 3));

            // Click '*' button
            Mouse.Click(uIItemButton3, new Point(20, 18));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(32, 16));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(59, 9));

            // Click '8' button
            Mouse.Click(uIItem8Button, new Point(30, 20));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(67, 16));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(14, 6));

            // Click '8' button
            Mouse.Click(uIItem8Button, new Point(29, 11));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(22, 10));

            // Click '/' button
            Mouse.Click(uIItemButton, new Point(22, 11));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(26, 17));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(70, 17));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(21, 13));

            // Click '8' button
            Mouse.Click(uIItem8Button, new Point(24, 18));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(24, 17));

            // Click '/' button
            Mouse.Click(uIItemButton, new Point(26, 15));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(19, 16));
        }
        
        /// <summary>
        /// TestOff - Use 'TestOffExpectedValues' to pass parameters into this method.
        /// </summary>
        public void TestOff()
        {
            #region Variable Declarations
            WpfWindow uIMyCalculatorv1Window = this.UIMyCalculatorv1Window;
            #endregion

            // Verify that the 'Enabled' property of 'MyCalculator v1' window equals 'True'
            Assert.AreEqual(this.TestOffExpectedValues.UIMyCalculatorv1WindowEnabled, uIMyCalculatorv1Window.Enabled, "DIsable");
        }
        
        /// <summary>
        /// Testing ke 5
        /// </summary>
        public void TestKalkulator5()
        {
            #region Variable Declarations
            WpfTitleBar uIMyCalculatorv1TitleBar = this.UIMyCalculatorv1Window.UIMyCalculatorv1TitleBar;
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            WpfButton uIItem1Button = this.UIMyCalculatorv1Window.UIItem1Button;
            WpfButton uIItemButton3 = this.UIMyCalculatorv1Window.UIItemButton3;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            WpfButton uIItem2Button = this.UIMyCalculatorv1Window.UIItem2Button;
            WpfButton uIItem4Button = this.UIMyCalculatorv1Window.UIItem4Button;
            WpfButton uIItem9Button = this.UIMyCalculatorv1Window.UIItem9Button;
            WpfButton uIRButton = this.UIMyCalculatorv1Window.UIRButton;
            WpfButton uIItemButton4 = this.UIMyCalculatorv1Window.UIItemButton4;
            WpfButton uIItem7Button = this.UIMyCalculatorv1Window.UIItem7Button;
            WpfButton uIItemButton = this.UIMyCalculatorv1Window.UIItemButton;
            WpfButton uIItem8Button = this.UIMyCalculatorv1Window.UIItem8Button;
            #endregion

            // Click 'MyCalculator v1' title bar
            Mouse.Click(uIMyCalculatorv1TitleBar, new Point(47, 4));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(19, 13));

            // Double-Click '1' button
            Mouse.DoubleClick(uIItem1Button, new Point(31, 9));

            // Double-Click '1' button
            Mouse.DoubleClick(uIItem1Button, new Point(31, 9));

            // Click '*' button
            Mouse.Click(uIItemButton3, new Point(27, 11));

            // Double-Click '1' button
            Mouse.DoubleClick(uIItem1Button, new Point(17, 6));

            // Double-Click '1' button
            Mouse.DoubleClick(uIItem1Button, new Point(17, 6));

            // Double-Click '1' button
            Mouse.DoubleClick(uIItem1Button, new Point(17, 6));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(35, 15));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(30, 19));

            // Double-Click '2' button
            Mouse.DoubleClick(uIItem2Button, new Point(34, 8));

            // Double-Click '2' button
            Mouse.DoubleClick(uIItem2Button, new Point(34, 8));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(34, 8));

            // Click '*' button
            Mouse.Click(uIItemButton3, new Point(25, 10));

            // Double-Click '2' button
            Mouse.DoubleClick(uIItem2Button, new Point(20, 22));

            // Double-Click '2' button
            Mouse.DoubleClick(uIItem2Button, new Point(20, 22));

            // Double-Click '2' button
            Mouse.DoubleClick(uIItem2Button, new Point(20, 22));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(24, 8));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(29, 8));

            // Click '4' button
            Mouse.Click(uIItem4Button, new Point(34, 15));

            // Double-Click '4' button
            Mouse.DoubleClick(uIItem4Button, new Point(34, 15));

            // Click '4' button
            Mouse.Click(uIItem4Button, new Point(34, 15));

            // Click '*' button
            Mouse.Click(uIItemButton3, new Point(27, 9));

            // Double-Click '4' button
            Mouse.DoubleClick(uIItem4Button, new Point(38, 21));

            // Double-Click '4' button
            Mouse.DoubleClick(uIItem4Button, new Point(38, 21));

            // Double-Click '4' button
            Mouse.DoubleClick(uIItem4Button, new Point(38, 21));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(38, 14));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(23, 9));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(42, 15));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(42, 14));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(39, 14));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(39, 14));

            // Click '*' button
            Mouse.Click(uIItemButton3, new Point(17, 9));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(26, 17));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(26, 17));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(26, 17));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(26, 17));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(56, 19));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(21, 13));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(30, 18));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(30, 18));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(30, 18));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(30, 18));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(30, 18));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(30, 18));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(33, 18));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(33, 18));

            // Click '*' button
            Mouse.Click(uIItemButton3, new Point(12, 9));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(31, 18));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(31, 18));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(30, 18));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(30, 18));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(30, 18));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(61, 17));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(40, 19));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(40, 19));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(40, 19));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(40, 19));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(40, 19));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(40, 19));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(40, 19));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(40, 19));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(40, 19));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(40, 19));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(40, 19));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(40, 19));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(40, 19));

            // Click 'R' button
            Mouse.Click(uIRButton, new Point(40, 19));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(23, 21));

            // Double-Click '1' button
            Mouse.DoubleClick(uIItem1Button, new Point(23, 19));

            // Double-Click '1' button
            Mouse.DoubleClick(uIItem1Button, new Point(23, 19));

            // Click '-' button
            Mouse.Click(uIItemButton4, new Point(27, 11));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(16, 14));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(44, 5));

            // Double-Click '7' button
            Mouse.DoubleClick(uIItem7Button, new Point(27, 15));

            // Click '*' button
            Mouse.Click(uIItemButton3, new Point(29, 19));

            // Double-Click '7' button
            Mouse.DoubleClick(uIItem7Button, new Point(17, 15));

            // Double-Click '7' button
            Mouse.DoubleClick(uIItem7Button, new Point(17, 15));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(44, 16));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(22, 18));

            // Double-Click '7' button
            Mouse.DoubleClick(uIItem7Button, new Point(24, 19));

            // Double-Click '7' button
            Mouse.DoubleClick(uIItem7Button, new Point(24, 19));

            // Click '7' button
            Mouse.Click(uIItem7Button, new Point(24, 19));

            // Double-Click '*' button
            Mouse.DoubleClick(uIItemButton3, new Point(20, 11));

            // Click '*' button
            Mouse.Click(uIItemButton3, new Point(20, 11));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(15, 16));

            // Double-Click '7' button
            Mouse.DoubleClick(uIItem7Button, new Point(30, 16));

            // Double-Click '7' button
            Mouse.DoubleClick(uIItem7Button, new Point(30, 16));

            // Click '7' button
            Mouse.Click(uIItem7Button, new Point(30, 16));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(61, 14));

            // Double-Click 'R' button
            Mouse.DoubleClick(uIRButton, new Point(32, 19));

            // Click 'R' button
            Mouse.Click(uIRButton, new Point(32, 19));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(29, 19));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(39, 21));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(30, 16));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(30, 16));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(30, 16));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(30, 16));

            // Click '*' button
            Mouse.Click(uIItemButton3, new Point(21, 19));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(21, 19));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(21, 19));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(21, 19));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(21, 19));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(58, 12));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(35, 21));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(25, 12));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(17, 21));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(17, 21));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(17, 21));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(17, 21));

            // Click '/' button
            Mouse.Click(uIItemButton, new Point(11, 24));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(18, 24));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(18, 24));

            // Double-Click '9' button
            Mouse.DoubleClick(uIItem9Button, new Point(18, 24));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(18, 24));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(45, 19));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(32, 15));

            // Double-Click '7' button
            Mouse.DoubleClick(uIItem7Button, new Point(35, 25));

            // Double-Click '7' button
            Mouse.DoubleClick(uIItem7Button, new Point(35, 25));

            // Click '*' button
            Mouse.Click(uIItemButton3, new Point(24, 17));

            // Double-Click '8' button
            Mouse.DoubleClick(uIItem8Button, new Point(19, 12));

            // Double-Click '8' button
            Mouse.DoubleClick(uIItem8Button, new Point(19, 12));

            // Double-Click '8' button
            Mouse.DoubleClick(uIItem8Button, new Point(19, 12));

            // Double-Click '8' button
            Mouse.DoubleClick(uIItem8Button, new Point(19, 12));

            // Double-Click '8' button
            Mouse.DoubleClick(uIItem8Button, new Point(19, 12));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(48, 13));
        }
        
        /// <summary>
        /// TestResultKalkulator5 - Use 'TestResultKalkulator5ExpectedValues' to pass parameters into this method.
        /// </summary>
        public void TestResultKalkulator5()
        {
            #region Variable Declarations
            WpfEdit uITBEdit = this.UIMyCalculatorv1Window.UITBEdit;
            #endregion

            // Verify that the 'Text' property of 'tb' text box equals '7777*8888888888=69128888881976'
            Assert.AreEqual(this.TestResultKalkulator5ExpectedValues.UITBEditText, uITBEdit.Text, "Test Belum Sesuai");
        }
        
        #region Properties
        public virtual TestResultKalkulatorExpectedValues TestResultKalkulatorExpectedValues
        {
            get
            {
                if ((this.mTestResultKalkulatorExpectedValues == null))
                {
                    this.mTestResultKalkulatorExpectedValues = new TestResultKalkulatorExpectedValues();
                }
                return this.mTestResultKalkulatorExpectedValues;
            }
        }
        
        public virtual TestResultKalkulator2ExpectedValues TestResultKalkulator2ExpectedValues
        {
            get
            {
                if ((this.mTestResultKalkulator2ExpectedValues == null))
                {
                    this.mTestResultKalkulator2ExpectedValues = new TestResultKalkulator2ExpectedValues();
                }
                return this.mTestResultKalkulator2ExpectedValues;
            }
        }
        
        public virtual TestResultKalkulator3ExpectedValues TestResultKalkulator3ExpectedValues
        {
            get
            {
                if ((this.mTestResultKalkulator3ExpectedValues == null))
                {
                    this.mTestResultKalkulator3ExpectedValues = new TestResultKalkulator3ExpectedValues();
                }
                return this.mTestResultKalkulator3ExpectedValues;
            }
        }
        
        public virtual TestOffExpectedValues TestOffExpectedValues
        {
            get
            {
                if ((this.mTestOffExpectedValues == null))
                {
                    this.mTestOffExpectedValues = new TestOffExpectedValues();
                }
                return this.mTestOffExpectedValues;
            }
        }
        
        public virtual TestResultKalkulator5ExpectedValues TestResultKalkulator5ExpectedValues
        {
            get
            {
                if ((this.mTestResultKalkulator5ExpectedValues == null))
                {
                    this.mTestResultKalkulator5ExpectedValues = new TestResultKalkulator5ExpectedValues();
                }
                return this.mTestResultKalkulator5ExpectedValues;
            }
        }
        
        public UIMyCalculatorv1Window UIMyCalculatorv1Window
        {
            get
            {
                if ((this.mUIMyCalculatorv1Window == null))
                {
                    this.mUIMyCalculatorv1Window = new UIMyCalculatorv1Window();
                }
                return this.mUIMyCalculatorv1Window;
            }
        }
        
        public UIMyCalculatorv1Window1 UIMyCalculatorv1Window1
        {
            get
            {
                if ((this.mUIMyCalculatorv1Window1 == null))
                {
                    this.mUIMyCalculatorv1Window1 = new UIMyCalculatorv1Window1();
                }
                return this.mUIMyCalculatorv1Window1;
            }
        }
        #endregion
        
        #region Fields
        private TestResultKalkulatorExpectedValues mTestResultKalkulatorExpectedValues;
        
        private TestResultKalkulator2ExpectedValues mTestResultKalkulator2ExpectedValues;
        
        private TestResultKalkulator3ExpectedValues mTestResultKalkulator3ExpectedValues;
        
        private TestOffExpectedValues mTestOffExpectedValues;
        
        private TestResultKalkulator5ExpectedValues mTestResultKalkulator5ExpectedValues;
        
        private UIMyCalculatorv1Window mUIMyCalculatorv1Window;
        
        private UIMyCalculatorv1Window1 mUIMyCalculatorv1Window1;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestResultKalkulator'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class TestResultKalkulatorExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of 'tb' text box equals '4-7=-3'
        /// </summary>
        public string UITBEditText = "4-7=-3";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestResultKalkulator2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class TestResultKalkulator2ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of 'tb' text box equals '02+-02=0'
        /// </summary>
        public string UITBEditText = "02+-02=0";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestResultKalkulator3'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class TestResultKalkulator3ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Enabled' property of 'MyCalculator v1' window equals 'True'
        /// </summary>
        public bool UIMyCalculatorv1WindowEnabled = true;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestOff'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class TestOffExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Enabled' property of 'MyCalculator v1' window equals 'True'
        /// </summary>
        public bool UIMyCalculatorv1WindowEnabled = true;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestResultKalkulator5'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class TestResultKalkulator5ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of 'tb' text box equals '7777*8888888888=69128888881976'
        /// </summary>
        public string UITBEditText = "7777*8888888888=69128888881976";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMyCalculatorv1Window : WpfWindow
    {
        
        public UIMyCalculatorv1Window()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MyCalculator v1";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MyCalculator v1");
            #endregion
        }
        
        #region Properties
        public WpfTitleBar UIMyCalculatorv1TitleBar
        {
            get
            {
                if ((this.mUIMyCalculatorv1TitleBar == null))
                {
                    this.mUIMyCalculatorv1TitleBar = new WpfTitleBar(this);
                    #region Search Criteria
                    this.mUIMyCalculatorv1TitleBar.SearchProperties[WpfTitleBar.PropertyNames.AutomationId] = "TitleBar";
                    this.mUIMyCalculatorv1TitleBar.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIMyCalculatorv1TitleBar;
            }
        }
        
        public WpfButton UIDelButton
        {
            get
            {
                if ((this.mUIDelButton == null))
                {
                    this.mUIDelButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIDelButton.SearchProperties[WpfButton.PropertyNames.Name] = "Del";
                    this.mUIDelButton.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIDelButton;
            }
        }
        
        public WpfButton UIItem8Button
        {
            get
            {
                if ((this.mUIItem8Button == null))
                {
                    this.mUIItem8Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem8Button.SearchProperties[WpfButton.PropertyNames.Name] = "8";
                    this.mUIItem8Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem8Button;
            }
        }
        
        public WpfButton UIItem7Button
        {
            get
            {
                if ((this.mUIItem7Button == null))
                {
                    this.mUIItem7Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem7Button.SearchProperties[WpfButton.PropertyNames.AutomationId] = "button7";
                    this.mUIItem7Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem7Button;
            }
        }
        
        public WpfButton UIItem4Button
        {
            get
            {
                if ((this.mUIItem4Button == null))
                {
                    this.mUIItem4Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem4Button.SearchProperties[WpfButton.PropertyNames.Name] = "4";
                    this.mUIItem4Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem4Button;
            }
        }
        
        public WpfButton UIItem5Button
        {
            get
            {
                if ((this.mUIItem5Button == null))
                {
                    this.mUIItem5Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem5Button.SearchProperties[WpfButton.PropertyNames.Name] = "5";
                    this.mUIItem5Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem5Button;
            }
        }
        
        public WpfButton UIItem6Button
        {
            get
            {
                if ((this.mUIItem6Button == null))
                {
                    this.mUIItem6Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem6Button.SearchProperties[WpfButton.PropertyNames.Name] = "6";
                    this.mUIItem6Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem6Button;
            }
        }
        
        public WpfButton UIItem9Button
        {
            get
            {
                if ((this.mUIItem9Button == null))
                {
                    this.mUIItem9Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem9Button.SearchProperties[WpfButton.PropertyNames.AutomationId] = "button9";
                    this.mUIItem9Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem9Button;
            }
        }
        
        public WpfButton UIItem3Button
        {
            get
            {
                if ((this.mUIItem3Button == null))
                {
                    this.mUIItem3Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem3Button.SearchProperties[WpfButton.PropertyNames.Name] = "3";
                    this.mUIItem3Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem3Button;
            }
        }
        
        public WpfButton UIItem2Button
        {
            get
            {
                if ((this.mUIItem2Button == null))
                {
                    this.mUIItem2Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem2Button.SearchProperties[WpfButton.PropertyNames.Name] = "2";
                    this.mUIItem2Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem2Button;
            }
        }
        
        public WpfButton UIItem1Button
        {
            get
            {
                if ((this.mUIItem1Button == null))
                {
                    this.mUIItem1Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem1Button.SearchProperties[WpfButton.PropertyNames.Name] = "1";
                    this.mUIItem1Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem1Button;
            }
        }
        
        public WpfButton UIItem0Button
        {
            get
            {
                if ((this.mUIItem0Button == null))
                {
                    this.mUIItem0Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem0Button.SearchProperties[WpfButton.PropertyNames.Name] = "0";
                    this.mUIItem0Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem0Button;
            }
        }
        
        public WpfButton UIRButton
        {
            get
            {
                if ((this.mUIRButton == null))
                {
                    this.mUIRButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIRButton.SearchProperties[WpfButton.PropertyNames.Name] = "R";
                    this.mUIRButton.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIRButton;
            }
        }
        
        public WpfButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton.SearchProperties[WpfButton.PropertyNames.Name] = "/";
                    this.mUIItemButton.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        
        public WpfButton UIItemButton1
        {
            get
            {
                if ((this.mUIItemButton1 == null))
                {
                    this.mUIItemButton1 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton1.SearchProperties[WpfButton.PropertyNames.Name] = "=";
                    this.mUIItemButton1.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton1;
            }
        }
        
        public WpfButton UIItemButton2
        {
            get
            {
                if ((this.mUIItemButton2 == null))
                {
                    this.mUIItemButton2 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton2.SearchProperties[WpfButton.PropertyNames.Name] = "+";
                    this.mUIItemButton2.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton2;
            }
        }
        
        public WpfButton UIItemButton3
        {
            get
            {
                if ((this.mUIItemButton3 == null))
                {
                    this.mUIItemButton3 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton3.SearchProperties[WpfButton.PropertyNames.Name] = "*";
                    this.mUIItemButton3.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton3;
            }
        }
        
        public WpfButton UIItemButton4
        {
            get
            {
                if ((this.mUIItemButton4 == null))
                {
                    this.mUIItemButton4 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton4.SearchProperties[WpfButton.PropertyNames.Name] = "-";
                    this.mUIItemButton4.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton4;
            }
        }
        
        public WpfEdit UITBEdit
        {
            get
            {
                if ((this.mUITBEdit == null))
                {
                    this.mUITBEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITBEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "tb";
                    this.mUITBEdit.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUITBEdit;
            }
        }
        
        public WpfButton UIOffButton
        {
            get
            {
                if ((this.mUIOffButton == null))
                {
                    this.mUIOffButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIOffButton.SearchProperties[WpfButton.PropertyNames.Name] = "Off";
                    this.mUIOffButton.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIOffButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfTitleBar mUIMyCalculatorv1TitleBar;
        
        private WpfButton mUIDelButton;
        
        private WpfButton mUIItem8Button;
        
        private WpfButton mUIItem7Button;
        
        private WpfButton mUIItem4Button;
        
        private WpfButton mUIItem5Button;
        
        private WpfButton mUIItem6Button;
        
        private WpfButton mUIItem9Button;
        
        private WpfButton mUIItem3Button;
        
        private WpfButton mUIItem2Button;
        
        private WpfButton mUIItem1Button;
        
        private WpfButton mUIItem0Button;
        
        private WpfButton mUIRButton;
        
        private WpfButton mUIItemButton;
        
        private WpfButton mUIItemButton1;
        
        private WpfButton mUIItemButton2;
        
        private WpfButton mUIItemButton3;
        
        private WpfButton mUIItemButton4;
        
        private WpfEdit mUITBEdit;
        
        private WpfButton mUIOffButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMyCalculatorv1Window1 : WinWindow
    {
        
        public UIMyCalculatorv1Window1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "MyCalculator v1";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MyCalculator v1");
            #endregion
        }
    }
}
